# ----------------------------------------------------------------------------------------------------------------------
# DOCUMENTATION: Sources
# Description: Defines the raw data sources for the project, mapping the dbt project to Snowflake tables.
# ----------------------------------------------------------------------------------------------------------------------

version: 2

sources:
    - name: uspto
      database: uspto_db
      schema: raw
      tables:
        - name: patent_assignment_xml
