terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
    random = {
      source  = "hashicorp/random"
      version = "~> 3.0"
    }
  }
}

provider "aws" {
  region = "us-east-1"
}

# 1. Random Suffix for Bucket Name
resource "random_id" "bucket_suffix" {
  byte_length = 4
}

# 2. The Data Lake Bucket
resource "aws_s3_bucket" "data_lake" {
  bucket        = "uspto-data-lake-${random_id.bucket_suffix.hex}"
  force_destroy = true
}

# 3. Versioning
resource "aws_s3_bucket_versioning" "data_lake_ver" {
  bucket = aws_s3_bucket.data_lake.id
  versioning_configuration {
    status = "Enabled"
  }
}

# 4. Block Public Access
resource "aws_s3_bucket_public_access_block" "block_public" {
  bucket                  = aws_s3_bucket.data_lake.id
  block_public_acls       = true
  block_public_policy     = true
  ignore_public_acls      = true
  restrict_public_buckets = true
}

# 5. The Python Uploader (IAM User)
resource "aws_iam_user" "uploader" {
  name = "uspto_python_uploader"
}

# 6. Uploader Permissions
resource "aws_iam_policy" "s3_write_policy" {
  name        = "uspto_s3_write_access"
  description = "Allows writing to the USPTO data lake bucket"

  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [
      {
        Effect = "Allow"
        Action = [
          "s3:PutObject",
          "s3:GetObject",
          "s3:ListBucket"
        ]
        Resource = [
          aws_s3_bucket.data_lake.arn,
          "${aws_s3_bucket.data_lake.arn}/*"
        ]
      }
    ]
  })
}

resource "aws_iam_user_policy_attachment" "attach_s3_write" {
  user       = aws_iam_user.uploader.name
  policy_arn = aws_iam_policy.s3_write_policy.arn
}

# 7. Generate Local .env file
resource "local_file" "generated_env" {
  content = <<EOT
# This file is auto-generated by Terraform.
AWS_BUCKET_NAME=${aws_s3_bucket.data_lake.bucket}
AWS_IAM_USER_NAME=${aws_iam_user.uploader.name}
AWS_IAM_SNOWFLAKE_ROLE=${aws_iam_role.snowflake_reader.arn}
# Note: Snowflake Role ARN is now handled in iam.tf output
EOT
  filename = "${path.module}/../../.env.generated"
}

# 8. Output Bucket Name
output "final_bucket_name" {
  value = aws_s3_bucket.data_lake.bucket
}